version: '3.8'

services:
  jenkins:
    image: custom-jenkins:latest
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Bind mount for Docker socket
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always

volumes:
  jenkins_home:

